### ISSUE TITLE
Types shared through `InferPageProps` are poorly serialized

### ISSUE THREAD

**Issue by Bricklou** [adonisjs/inertia#18]
### Package version

1.0.0-25

### Describe the bug

I have the following code:
```ts
export default class Game extends BaseModel {
  @column({ isPrimary: true })
  declare id: number

  @column()
  declare name: string

  @column()
  declare description: string
}
```

But, when passed to `InferPageProps` like below:
```ts
const games = paginatedGames.serialize()
return inertia.render('admin/games/list', { games })
```

The resulting type is : 
```ts
type GamesListProps = {
    games: SerializeObject<{
        meta: any;
        data: ModelObject[];
    }>;
}
```

Is there any possible way to get something more explicit when inferring the type that would be usable for the frontend?

**Comment by Julien-R44** [comment]
No, actually, the problem is more about Lucid and the `serialize` method, which arent typesafe, rather than InferPageProps. The return type of `paginatedGames.serialize()` is exactly the one you get with InferPageProps.

If you want more precise types for your models, you'll need to type them manually or use some kind of DTO

**Comment by Bricklou** [comment]
Ok! Thank you for the clarification.

**Comment by Julien-R44** [comment]
Let me show you a few examples of how to deal with this problem, in case other future readers come across this issue

1st solution: manually type the `serialize()`. Because `serialize()` just returns a `Record<string, any>` so we have no way of automatically inferring the type. We need to help Typescript a little bit.

```ts
const user = users.serialize() as {
    id: number
    name: string 
}

return inertia.render('user/edit', { user })
```

2nd solution, use a DTOs / Presenter pattern. Quite similar to [Laravel's API resources](https://laravel.com/docs/11.x/eloquent-resources) if you want to know a bit more about that. I would say this is generally the preferred method: in addition to benefiting from typesafety, you add a layer of transformation and indirection that allows you to decouple your model and your view: 

```ts
export class UserPresenter {
  toJson(user: user) {
    return {
      id: user.id,
      name: user.name
    }
  }
}

@inject()
export default class UsersController {
  constructor(protected presenter: UserPresenter) {}

  index({ inertia }) {
    const users = await User.all()
    
   return inertia.render('users', {
     users: users.map(user => this.presenter.toJson(user))
   })
  }
}
```
