### ISSUE TITLE
Error passing model with @computed() or pagination to Inertia.js

### ISSUE THREAD

**Issue by lncitador** [adonisjs/inertia#19]
### Package version

1.0.0-25

### Describe the bug

I'm experiencing an error when passing models that contain `@computed()` or when using pagination with Inertia.js in my project. It seems that an error is occurring within the `@adonisjs/inertiajs` package.

The problem arises when a model with `@computed()` is passed to Inertia.js, resulting in a process failure. In addition, when using pagination, the same error also occurs.

I would like to request a review of this issue and possible fixes in the `@adonisjs/inertiajs` package to properly handle these scenarios.

### Reproduction repo

https://github.com/lncitador/computed-and-pagination-error

**Comment by Julien-R44** [comment]
Hello

You just need to serialize the data you send, otherwise you will get hydration errors
Your TestsController should be : 

```ts
  async handle({ inertia, auth }: HttpContext) {
    const posts = await auth.user?.related('posts').query().paginate(1, 10)
    return inertia.render('test', { posts: posts?.serialize(), user: auth.user })
  }
  ```

and that's it

**Comment by lncitador** [comment]
right, I know that you have to give .serialize(), but besides the fact that in the end it will infer a ModelObject type because of the method, this ends up being a nuisance when you have to do it over and over again in every controller handle, so I created a serialize function that already infers the type, take a look at the 'fixed' branch.

![image](https://github.com/adonisjs/inertia/assets/55416536/13c48f26-90f3-458f-9e30-f96369ecb447)

**Comment by lncitador** [comment]
with this I created another branch for you to test my changes that I sent pull resquet, take a look at the 'feature' branch

**Comment by Julien-R44** [comment]
Actually, I don't think it's a good idea to handle this directly in @adonisjs/inertia:

- We tightly couple @adonisjs/inertia with Lucid. If I use Kysely instead of Lucid in my application, then your fix won't work. I'll inevitably need to install @adonisjs/lucid.
- Here, you're only handling serialization specific to Lucid. But the problem will remain the same if we send any other class or object that needs to be serialized. even for a simple `Date`. If you're doing SSR and you don't serialize your `Date` instance before calling `inertia.render`, you'll also get a hydration error. The same goes for `Map`, `Set`, or any other non-primitives

That's why, for me, the responsibility of serialization should be on the user side, not on the @adonisjs/inertia side

**Comment by lncitador** [comment]
`@adonisjs/inertia` being dependent on `lucid` is complicated when someone wants to use another querybuilder, about the serialization of non-primitives I was developing a solution with `superjson`, which I had used in another lib. but the `lucid` issue made me review everything and I saw that it is impossible to have this feature of automatic serialization

**Comment by Julien-R44** [comment]
Yeah I don't think we should impose superjson or similar alternative, if people want to use it then they can quite easily add it on their side

In any case, thanks for the detailed reproduction! Same goes for PR
